server:
  port: 8080
spring:
  profiles:
    active: local
  data:
    mongodb:
      uri: ${MONGO_URL:mongodb://localhost:27017/dev}
  servlet:
    multipart:
      max-file-size: 1024KB
      max-request-size: 1024KB